BLOCOS_SPED = {
    "Abertura e Identificação": ["0000"],
    "Tabelas": ["0140", "0150", "0190", "0200", "0400"],
    "Bloco A": ["A100", "A111", "A170"],
    "Bloco C": ["C100", "C111", "C120", "C170", "C175", "C180", "C181", "C185", "C186", "C190"],
    "Bloco D": ["D100", "D105", "D200", "D205", "D500", "D505"],
    "Bloco F": ["F100", "F120", "F130", "F150", "F200", "F205", "F210", "F600", "F700", "F800"],
    "Bloco M": ["M100", "M105", "M110", "M115", "M200", "M205", "M210", "M211", "M215", "M220","M225", "M230", "M235", "M300", "M305", "M350", "M400", "M410", "M500", "M505","M600", "M605", "M610", "M615"],        
    "Bloco P": ["P100", "P200", "P210"]
}

LAYOUT_REGISTROS = {
    # BLOCO 0 - ABERTURA, IDENTIFICAÇÃO E REFERÊNCIAS
    "0000": ["REG", "COD_VER", "COD_FIN", "DT_INI", "DT_FIN", "NOME", "CNPJ", "UF", "COD_MUN", "SUFRAMA", "IND_NAT_PJ", "IND_ATIV"],
    "0140": ["REG", "COD_EST", "NOME", "CNPJ", "UF", "IE", "COD_MUN", "IM", "SUFRAMA"],
    "0150": ["REG", "COD_PART", "NOME", "COD_PAIS", "CNPJ", "CPF", "IE", "COD_MUN", "SUFRAMA", "END", "NUM", "COMPL", "BAIRRO"],
    "0190": ["REG", "UNID", "DESCR"],
    "0200": ["REG", "COD_ITEM", "DESCR_ITEM", "COD_BARRA", "COD_ANT_ITEM", "UNID_INV", "TIPO_ITEM", "COD_NCM", "EX_IPI", "COD_GEN", "COD_LST", "ALIQ_ICMS"],
    "0400": ["REG", "COD_NAT", "DESCR_NAT"],

    # BLOCO A - DOCUMENTOS DE SERVIÇOS
    "A100": ["REG", "IND_OPER", "IND_EMIT", "COD_PART", "COD_SIT", "SER", "SUB", "NUM_DOC", "CHV_NFE", "DT_DOC", "DT_EXE_SERV", "VL_DOC", "VL_DESC", "VL_BC_PIS", "VL_PIS", "VL_BC_COFINS", "VL_COFINS"],
    "A111": ["REG", "NUM_DOC", "NUM_PROC", "IND_PROC"],  # NUM_DOC relaciona com A100
    "A170": ["REG", "NUM_DOC", "NUM_ITEM", "COD_ITEM", "DESCR_COMPL", "VL_ITEM", "VL_DESC", "NAT_BC_CRED", "IND_ORIG_CRED", "CST_PIS", "VL_BC_PIS", "ALIQ_PIS", "VL_PIS", "CST_COFINS", "VL_BC_COFINS", "ALIQ_COFINS", "VL_COFINS", "COD_CTA"],

    # BLOCO C - DOCUMENTOS DE MERCADORIAS
    "C100": ["REG", "IND_OPER", "IND_EMIT", "COD_PART", "COD_MOD", "COD_SIT", "SER", "NUM_DOC", "CHV_NFE", "DT_DOC", "DT_ENT", "VL_DOC", "IND_PGTO", "VL_DESC", "VL_ABAT_NT", "VL_MERC", "VL_FRT", "VL_SEG", "VL_OUT_DA", "VL_BC_ICMS", "VL_ICMS", "VL_BC_ICMS_ST", "VL_ICMS_ST", "VL_IPI", "VL_PIS", "VL_COFINS"],
    "C111": ["REG", "NUM_DOC", "NUM_PROC", "IND_PROC"],   # vincula com C100
    "C120": ["REG", "NUM_DOC", "COD_DOC_IMP", "NUM_DOC_IMP", "VL_PIS", "VL_COFINS"],  # vincula com C100
    "C170": ["REG", "NUM_DOC", "NUM_ITEM", "COD_ITEM", "DESCR_COMPL", "QTD", "UNID", "VL_ITEM", "VL_DESC", "IND_ORIG_CRED", "CST_PIS", "VL_BC_PIS", "ALIQ_PIS", "VL_PIS", "CST_COFINS", "VL_BC_COFINS", "ALIQ_COFINS", "VL_COFINS", "COD_CTA"],  # vincula com C100
    "C175": ["REG", "NUM_DOC", "CFOP", "VL_OPR", "VL_DESC", "CST_PIS", "VL_BC_PIS", "ALIQ_PIS", "VL_PIS", "CST_COFINS", "VL_BC_COFINS", "ALIQ_COFINS", "VL_COFINS"], # vincula com C100
    "C180": ["REG", "COD_MOD", "DT_DOC_INI", "DT_DOC_FIN", "COD_ITEM", "VL_CANC", "VL_DESC", "VL_MERC", "VL_OUT_DA", "VL_ICMS", "VL_PIS", "VL_COFINS"],
    "C181": ["REG", "NUM_DOC", "COD_ITEM", "QTD", "UNID", "VL_ITEM", "VL_DESC", "VL_PIS", "VL_COFINS"], # vincula com C180
    "C185": ["REG", "COD_MOD", "DT_DOC_INI", "DT_DOC_FIN", "COD_ITEM", "VL_CANC", "VL_DESC", "VL_MERC", "VL_OUT_DA", "VL_ICMS", "VL_PIS", "VL_COFINS"],
    "C186": ["REG", "NUM_DOC", "COD_ITEM", "QTD", "UNID", "VL_ITEM", "VL_DESC", "VL_PIS", "VL_COFINS"], # vincula com C185
    "C190": ["REG", "NUM_DOC", "CST_ICMS", "CFOP", "ALIQ_ICMS", "VL_OPR", "VL_BC_ICMS", "VL_ICMS", "VL_BC_ICMS_ST", "VL_ICMS_ST", "VL_RED_BC", "VL_IPI", "COD_OBS"], # vincula com C100

    # BLOCO D - TRANSPORTE E COMUNICAÇÃO
    "D100": ["REG", "IND_OPER", "IND_EMIT", "COD_PART", "COD_MOD", "COD_SIT", "SER", "SUB", "NUM_DOC", "CHV_NFE", "DT_DOC", "DT_A_P", "VL_DOC", "VL_DESC", "VL_SERV", "VL_SERV_NT", "VL_TERC", "VL_DA", "VL_BC_ICMS", "VL_ICMS", "VL_PIS", "VL_COFINS"],
    "D105": ["REG", "NUM_DOC", "CST_PIS", "VL_ITEM", "VL_BC_PIS", "ALIQ_PIS", "VL_PIS", "CST_COFINS", "VL_BC_COFINS", "ALIQ_COFINS", "VL_COFINS"], # vincula com D100
    "D200": ["REG", "COD_MOD", "COD_SIT", "SER", "SUB", "NUM_DOC_INI", "NUM_DOC_FIN", "DT_DOC", "VL_DOC", "VL_DESC", "VL_SERV", "VL_SERV_NT", "VL_TERC", "VL_DA", "VL_BC_ICMS", "VL_ICMS", "VL_PIS", "VL_COFINS"],
    "D205": ["REG", "NUM_DOC", "CST_PIS", "VL_ITEM", "VL_BC_PIS", "ALIQ_PIS", "VL_PIS", "CST_COFINS", "VL_BC_COFINS", "ALIQ_COFINS", "VL_COFINS"], # vincula com D200
    "D500": ["REG", "IND_OPER", "IND_EMIT", "COD_PART", "COD_MOD", "COD_SIT", "SER", "SUB", "NUM_DOC", "CHV_NFE", "DT_DOC", "DT_A_P", "VL_DOC", "VL_DESC", "VL_SERV", "VL_SERV_NT", "VL_TERC", "VL_DA", "VL_BC_ICMS", "VL_ICMS", "VL_PIS", "VL_COFINS"],
    "D505": ["REG", "NUM_DOC", "CST_PIS", "VL_ITEM", "VL_BC_PIS", "ALIQ_PIS", "VL_PIS", "CST_COFINS", "VL_BC_COFINS", "ALIQ_COFINS", "VL_COFINS"], # vincula com D500

    # BLOCO F - OUTRAS OPERAÇÕES E CRÉDITOS
    "F100": ["REG", "IND_OPER", "COD_PART", "VL_OPER", "CST_PIS", "VL_BC_PIS", "ALIQ_PIS", "VL_PIS", "CST_COFINS", "VL_BC_COFINS", "ALIQ_COFINS", "VL_COFINS"],
    "F120": ["REG", "NUM_DOC", "NAT_BC_CRED", "VL_BC_PIS", "ALIQ_PIS", "VL_PIS", "VL_BC_COFINS", "ALIQ_COFINS", "VL_COFINS"],
    "F130": ["REG", "NAT_BC_CRED", "VL_BC_PIS", "ALIQ_PIS", "VL_PIS", "VL_BC_COFINS", "ALIQ_COFINS", "VL_COFINS"],
    "F150": ["REG", "VL_REC_EXP", "CST_PIS", "VL_BC_PIS", "ALIQ_PIS", "VL_PIS", "CST_COFINS", "VL_BC_COFINS", "ALIQ_COFINS", "VL_COFINS"],
    "F200": ["REG", "VL_CRED_PRESUMIDO_PIS", "VL_CRED_PRESUMIDO_COFINS"],
    "F205": ["REG", "NUM_DOC", "VL_BC_PIS", "ALIQ_PIS", "VL_PIS", "VL_BC_COFINS", "ALIQ_COFINS", "VL_COFINS"], # vincula com F200
    "F210": ["REG", "NUM_DOC", "VL_BC_PIS", "ALIQ_PIS", "VL_PIS", "VL_BC_COFINS", "ALIQ_COFINS", "VL_COFINS"], # vincula com F200
    "F600": ["REG", "VL_REC", "VL_PIS", "VL_COFINS"],
    "F700": ["REG", "VL_CRED_PIS", "VL_CRED_COFINS"],
    "F800": ["REG", "COD_ITEM", "VL_REC", "VL_PIS", "VL_COFINS"],

    # BLOCO M - APURAÇÃO PIS/COFINS
    "M100": ["REG", "COD_CRED", "VL_CRED", "VL_AJUS_ACRES", "VL_AJUS_REDUC", "VL_CRED_DIFERIDO", "VL_CRED_DISP", "IND_DESC_CRED", "VL_CRED_DESC", "SLD_CRED"],
    "M105": ["REG", "COD_CRED", "NAT_BC_CRED", "CST_PIS", "VL_BC_PIS", "ALIQ_PIS", "VL_PIS", "CST_COFINS", "VL_BC_COFINS", "ALIQ_COFINS", "VL_COFINS"], # vincula com M100
    "M110": ["REG", "COD_CRED", "IND_AJ", "VL_AJ", "COD_AJ", "NUM_DOC", "DESCR_AJ", "DT_REF"], # vincula com M100
    "M115": ["REG", "COD_CRED", "VL_PIS", "VL_COFINS"], # vincula com M100
    "M200": ["REG", "COD_CONT", "VL_TOT_CONT_NCUMUL", "VL_TOT_CONT_CUMUL", "VL_CONT_CRED_DIF", "VL_CONT_DIF", "VL_CONT_A_REC"],
    "M205": ["REG", "COD_CONT", "VL_PIS", "VL_COFINS"], # vincula com M200
    "M210": ["REG", "COD_CONT", "VL_CONT_APUR", "VL_AJUS_ACRES", "VL_AJUS_REDUC", "VL_CONT_DIFER", "VL_CONT_A_REC"],
    "M211": ["REG", "COD_CONT", "VL_PIS", "VL_COFINS"], # vincula com M210
    "M215": ["REG", "COD_CONT", "COD_AJ", "DESCR_AJ", "VL_AJ"], # vincula com M210
    "M220": ["REG", "COD_CONT", "VL_CRED_APUR", "VL_AJUS_ACRES", "VL_AJUS_REDUC", "VL_CRED_DIFER", "VL_CRED_DISP"],
    "M225": ["REG", "COD_CONT", "VL_PIS", "VL_COFINS"], # vincula com M220
    "M230": ["REG", "COD_CONT", "VL_TOT_CRED_NCUMUL", "VL_TOT_CRED_CUMUL"],
    "M235": ["REG", "COD_CONT", "VL_PIS", "VL_COFINS"], # vincula com M230
    "M300": ["REG", "COD_CONT", "VL_TOT_CONT_NCUMUL", "VL_TOT_CONT_CUMUL"],
    "M305": ["REG", "COD_CONT", "VL_PIS", "VL_COFINS"], # vincula com M300
    "M350": ["REG", "COD_CONT", "VL_BC_CPRB", "ALIQ_PIS", "VL_PIS", "ALIQ_COFINS", "VL_COFINS"],
    "M400": ["REG", "COD_CONT", "VL_CRED_PIS", "VL_CRED_COFINS"],
    "M410": ["REG", "COD_CONT", "VL_PIS", "VL_COFINS"], # vincula com M400
    "M500": ["REG", "COD_CONT", "VL_CRED_PIS", "VL_CRED_COFINS"],
    "M505": ["REG", "COD_CONT", "VL_PIS", "VL_COFINS"], # vincula com M500
    "M600": ["REG", "COD_CONT", "VL_CONT_PIS", "VL_CONT_COFINS"],
    "M605": ["REG", "COD_CONT", "VL_PIS", "VL_COFINS"], # vincula com M600
    "M610": ["REG", "COD_CONT", "VL_CONT_PIS", "VL_CONT_COFINS"],
    "M615": ["REG", "COD_CONT", "VL_PIS", "VL_COFINS"], # vincula com M610

    # BLOCO P - CPRB
    "P100": ["REG", "VL_REC_BRUTA", "VL_EXC_REC_BRUTA", "VL_REC_BRUTA_TOTAL", "COD_ATIV_ECON"],
    "P200": ["REG", "VL_BC_CPRB", "ALIQ_CPRB", "VL_CPRB", "VL_AJUS_ACRES", "VL_AJUS_REDUC", "VL_CPRB_APUR"],
    "P210": ["REG", "COD_CONT", "VL_PIS", "VL_COFINS"] # vincula com P200
}